#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures new server
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '22i\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
