#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures new server
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '22i\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
