#!/usr/bin/env bash
# configure load balancer
sudo apt-get -y update
sudo apt-get y install haproxy=1.5\*
echo -e "defaults
\tlisten 355-lb-01
frontend
\tbind *:80
\tmode http
backend
\toption http
\tbalance roundrobin
\tserver 355-web-01 35.237.244.23 check
server 355-web-02 35.196.221.206 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
