#!/usr/bin/env bash
# configure load balancer
sudo apt-get -y update
sudo apt-get y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
FILE=/etc/haproxy/haproxy.cfg
echo "listen 355-lb-01" | sudo tee -a $FILE
echo "bind *:80" | sudo tee -a $FILE
echo "mode http" | sudo tee -a $FILE
echo "option http" | sudo tee -a $FILE
echo "balance roundrobin" | sudo tee -a $FILE
echo "server 355-web-01 35.237.244.23 check" | sudo tee -a $FILE
echo "server 355-web-02 35.196.221.206 check" | sudo tee -a $FILE
sudo service haproxy restart
