#!/usr/bin/env bash
# manages 'manage_my_process'
# argument 'start' starts the process, creates a file containing PID, displays message
# argument 'stop' stops process, deletes file, displays message
# argument 'restart' stops process, deletes file, starts process, creates new file, displays message

FILE=/var/run/my_process.pid
case $1 in
    start)
	./manage_my_process &
	echo $$ > $FILE
	echo "manage_my_process started"
	;;
    stop)
        pkill -f ./manage_my_process
        sudo rm $FILE
        echo "manage_my_process stopped"
	;;
    restart)
        pkill -f ./manage_my_process
        sudo rm $FILE
	./manage_my_process &
        echo $$ > $FILE
        echo "manage_my_process restarted"
	;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
