#!/usr/bin/env bash
# displays contents of file /etc/passwd using while loop and IFS

FILE=/etc/passwd
while ISF=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < $FILE
