#!/usr/bin/env bash
# redirects /redirect_me to another page
sudo apt-get update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
file2=/etc/ngnix/sites-available/default
old=/redirect_me
new=https://www.youtube.com/watch?v=QH2-TGUlwu4
echo "Holberton School" | sudo tee $file1
sudo sed -i "37 location $old {\nreturn 301 $new;\n}\n" $file2
sudo service nginx restart
