#!/usr/bin/env bash
# redirects /redirect_me to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
cmd="\nlocation /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "37i \$cmd" /etc/ngnix/sites-available/default
sudo service nginx restart
