#!/usr/bin/env bash
# custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page :(" | sudo tee /usr/share/nginx/html/custom_404.html
cmd="\nerror_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal\n;}"
sudo sed -i "40i $cmd" /etc/ngnix/sites-available/default
sudo service nginx restart
