#!/usr/bin/env bash
# changes user to nginx in nginx config file
sudo pkill -f apache2
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
