#!/usr/bin/env bash
# changes user to nginx in nginx config file
sudo pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
